import ExcelJS from "exceljs";
import { requireUser } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
const C = { ink: "17251F", muted: "6D7C76", green: "185D43", greenSoft: "E8F2ED", orange: "DF6B22", orangeSoft: "FFF0E5", red: "C9483D", redSoft: "FCE9E7", amber: "B7851E", amberSoft: "FFF3D9", white: "FFFFFF", bg: "F4F7F5", panel: "FFFFFF", line: "D9E1DD" };
const statusLabel: Record<string, string> = { OPEN: "Open", PENDING_VERIFICATION: "Menunggu Verifikasi", REVISION_REQUIRED: "Perlu Revisi", CLOSED: "Close" };
const fill = (argb: string) => ({ type: "pattern" as const, pattern: "solid" as const, fgColor: { argb } });
const border = { top: { style: "thin" as const, color: { argb: C.line } }, bottom: { style: "thin" as const, color: { argb: C.line } }, left: { style: "thin" as const, color: { argb: C.line } }, right: { style: "thin" as const, color: { argb: C.line } } };
const headerStyle = { font: { name: "Aptos", size: 9, bold: true, color: { argb: C.white } }, fill: fill(C.green), alignment: { vertical: "middle" as const, horizontal: "center" as const, wrapText: true }, border: { bottom: { style: "medium" as const, color: { argb: C.orange } } } };
const bars = (value: number, max: number, length = 16) => value ? "█".repeat(Math.max(1, Math.round(value / Math.max(1, max) * length))) : "·";
const ageDays = (date: string) => Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 86400000));
const writeRow = (sheet: ExcelJS.Worksheet, row: number, startColumn: number, values: unknown[]) => values.forEach((value, index) => { sheet.getCell(row, startColumn + index).value = value as ExcelJS.CellValue; });
const styleRow = (sheet: ExcelJS.Worksheet, row: number, startColumn: number, count: number, style: Partial<ExcelJS.Style>) => { for (let index = 0; index < count; index += 1) sheet.getCell(row, startColumn + index).style = style; };

function titleBand(sheet: ExcelJS.Worksheet, title: string, subtitle: string, endColumn: string) {
  sheet.mergeCells(`A1:${endColumn}2`); const titleCell = sheet.getCell("A1"); titleCell.value = title; titleCell.fill = fill(C.green); titleCell.font = { name: "Aptos Display", size: 22, bold: true, color: { argb: C.white } }; titleCell.alignment = { vertical: "middle" };
  sheet.mergeCells(`A3:${endColumn}3`); const sub = sheet.getCell("A3"); sub.value = subtitle; sub.font = { name: "Aptos", size: 10, color: { argb: C.muted } }; sub.fill = fill(C.bg); sub.alignment = { vertical: "middle" };
  sheet.getRow(1).height = 25; sheet.getRow(2).height = 16; sheet.getRow(3).height = 24;
}

function panelTitle(sheet: ExcelJS.Worksheet, range: string, title: string, note: string) {
  sheet.mergeCells(range); const cell = sheet.getCell(range.split(":")[0]); cell.value = `${title}\n${note}`; cell.fill = fill(C.panel); cell.font = { name: "Aptos", size: 10, bold: true, color: { argb: C.ink } }; cell.alignment = { vertical: "middle", wrapText: true }; cell.border = border;
}

function styleTable(sheet: ExcelJS.Worksheet, headerRow = 1) {
  sheet.getRow(headerRow).eachCell((cell) => { cell.style = headerStyle; }); sheet.getRow(headerRow).height = 32;
  sheet.eachRow((row) => row.eachCell((cell) => { cell.font = { name: "Aptos", size: cell.font?.size ?? 9, ...cell.font }; if (row.number > headerRow) cell.border = { bottom: { style: "hair", color: { argb: C.line } } }; }));
}

export async function GET() {
  const ctx = await requireUser();
  if (!ctx) return Response.json({ error: "Unauthorized" }, { status: 401 });
  if (ctx.profile.role !== "SUPER_ADMIN") return Response.json({ error: "Export hanya tersedia untuk master admin." }, { status: 403 });
  const [findingsResult, companiesResult, categoriesResult, sectionsResult, profilesResult, accessResult] = await Promise.all([
    ctx.db.from("findings").select("finding_number,finding_date,unit_number,detailed_description,current_status,target_date,closed_at,source_type,legacy_original_number,companies(code,name),categories(name,category_group),sections(name)").order("finding_date").order("finding_number"),
    ctx.db.from("companies").select("id,code,name,active").order("code"),
    ctx.db.from("categories").select("id,name,short_name,category_group,default_evidence_requirement,active").order("name"),
    ctx.db.from("sections").select("id,name,active").order("name"),
    ctx.db.from("profiles").select("id,email,full_name,nik,role,active,created_at").order("full_name"),
    ctx.db.from("user_company_access").select("user_id,companies(code)"),
  ]);
  const failed = [findingsResult, companiesResult, categoriesResult, sectionsResult, profilesResult, accessResult].find((result) => result.error);
  if (failed?.error) return Response.json({ error: failed.error.message }, { status: 500 });
  const rows = (findingsResult.data ?? []) as any[]; const companies = companiesResult.data ?? []; const categories = categoriesResult.data ?? []; const sections = sectionsResult.data ?? []; const profiles = profilesResult.data ?? []; const access = accessResult.data ?? [];
  const active = rows.filter((row) => row.current_status !== "CLOSED"); const closed = rows.filter((row) => row.current_status === "CLOSED"); const revision = rows.filter((row) => row.current_status === "REVISION_REQUIRED"); const overdue = active.filter((row) => row.target_date && new Date(row.target_date).getTime() < Date.now()); const currentMonth = new Date().toISOString().slice(0, 7); const closedMonth = closed.filter((row) => row.closed_at?.slice(0, 7) === currentMonth).length;
  const monthlyMap = new Map<string, { open: number; closed: number }>(); rows.forEach((row) => { const key = row.finding_date.slice(0, 7); const item = monthlyMap.get(key) ?? { open: 0, closed: 0 }; item.open += 1; if (row.current_status === "CLOSED") item.closed += 1; monthlyMap.set(key, item); }); const monthly = [...monthlyMap.entries()].sort().slice(-8).map(([key, value]) => ({ name: new Date(`${key}-01T00:00:00`).toLocaleDateString("id-ID", { month: "short", year: "numeric" }), ...value }));
  const repeatMap = new Map<string, { unit: string; company: string; total: number; outstanding: number; last: string }>(); rows.filter((row) => row.unit_number?.trim()).forEach((row) => { const unit = row.unit_number.trim(), company = row.companies?.code || "—", key = `${company}:${unit}`, item = repeatMap.get(key) ?? { unit, company, total: 0, outstanding: 0, last: row.finding_date }; item.total += 1; item.outstanding += row.current_status === "CLOSED" ? 0 : 1; if (row.finding_date > item.last) item.last = row.finding_date; repeatMap.set(key, item); }); const repeats = [...repeatMap.values()].filter((item) => item.total > 1).sort((a, b) => b.outstanding - a.outstanding || b.total - a.total).slice(0, 10);
  const companyGroups = rows.reduce<Record<string, { total: number; closed: number }>>((acc, row) => { const key = row.companies?.code || "—"; acc[key] ??= { total: 0, closed: 0 }; acc[key].total += 1; acc[key].closed += row.current_status === "CLOSED" ? 1 : 0; return acc; }, {}); const companyRate = Object.entries(companyGroups).map(([name, item]) => ({ name, value: item.total ? item.closed / item.total : 0 })).sort((a, b) => b.value - a.value);
  const countBy = (values: string[]) => Object.entries(values.reduce<Record<string, number>>((acc, value) => { acc[value] = (acc[value] || 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1]);
  const aging = [{ name: "0–3 hari", value: 0 }, { name: "4–7 hari", value: 0 }, { name: "8–14 hari", value: 0 }, { name: ">14 hari", value: 0 }]; active.forEach((row) => { const age = ageDays(row.finding_date); aging[age <= 3 ? 0 : age <= 7 ? 1 : age <= 14 ? 2 : 3].value += 1; });

  const workbook = new ExcelJS.Workbook(); workbook.creator = "SISOBER"; workbook.company = "Safety Inspection Unit and Behavior Driver"; workbook.created = new Date(); workbook.calcProperties.fullCalcOnLoad = true;
  const dashboard = workbook.addWorksheet("DASHBOARD", { views: [{ showGridLines: false }], pageSetup: { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 2, paperSize: 9, margins: { left: .2, right: .2, top: .3, bottom: .3, header: .1, footer: .1 } } }); dashboard.columns = [16, 11, 11, 15, 15, 6, 10, 22, 14, 12, 10, 3, 30, 16].map((width) => ({ width })); titleBand(dashboard, "SISOBER · SAFETY INTELLIGENCE", `Safety Inspection Unit and Behavior Driver  |  Exported ${new Date().toLocaleString("id-ID")}  |  Select a panel and paste into PowerPoint as Picture`, "N");
  const kpis = [{ label: "TEMUAN TERBUKA", value: active.length, note: `${overdue.length} melewati target`, tone: C.orangeSoft, accent: C.orange }, { label: "DITUTUP BULAN INI", value: closedMonth, note: `${closed.length} selesai seluruhnya`, tone: C.greenSoft, accent: C.green }, { label: "OVERDUE", value: overdue.length, note: "perlu tindakan segera", tone: C.redSoft, accent: C.red }, { label: "REJECTED CLOSURE", value: revision.length, note: "menunggu perbaikan bukti", tone: C.amberSoft, accent: C.amber }];
  [[1, 3, "A"], [5, 7, "E"], [9, 11, "I"], [13, 14, "M"]].forEach(([startColumn, endColumn, column], index) => {
    const kpi = kpis[index];
    for (let row = 5; row <= 8; row += 1) {
      for (let col = Number(startColumn); col <= Number(endColumn); col += 1) {
        const cell = dashboard.getCell(row, col);
        cell.fill = fill(kpi.tone);
        if (row === 5) cell.border = { top: border.top };
        if (row === 8) cell.border = { ...cell.border, bottom: border.bottom };
        if (col === Number(startColumn)) cell.border = { ...cell.border, left: border.left };
        if (col === Number(endColumn)) cell.border = { ...cell.border, right: { style: "medium", color: { argb: kpi.accent } } };
      }
    }
    dashboard.getCell(`${column}5`).value = kpi.label;
    dashboard.getCell(`${column}5`).font = { name: "Aptos", size: 9, bold: true, color: { argb: C.muted } };
    dashboard.getCell(`${column}6`).value = kpi.value;
    dashboard.getCell(`${column}6`).font = { name: "Aptos Display", size: 22, bold: true, color: { argb: C.ink } };
    dashboard.getCell(`${column}6`).numFmt = "#,##0";
    dashboard.getCell(`${column}8`).value = kpi.note;
    dashboard.getCell(`${column}8`).font = { name: "Aptos", size: 8, color: { argb: C.muted } };
    dashboard.getCell(`${column}5`).alignment = dashboard.getCell(`${column}6`).alignment = dashboard.getCell(`${column}8`).alignment = { vertical: "middle" };
  });
  panelTitle(dashboard, "A10:E11", "TERBUKA VS DITUTUP", "Pergerakan temuan bulanan"); writeRow(dashboard, 12, 1, ["Periode", "Terbuka", "Ditutup", "Terbuka", "Ditutup"]); styleRow(dashboard, 12, 1, 5, headerStyle); const trendMax = Math.max(1, ...monthly.flatMap((item) => [item.open, item.closed])); monthly.forEach((item, index) => { const row = 13 + index; writeRow(dashboard, row, 1, [item.name, item.open, item.closed, bars(item.open, trendMax, 13), bars(item.closed, trendMax, 13)]); dashboard.getCell(`D${row}`).font = { color: { argb: C.orange }, size: 8 }; dashboard.getCell(`E${row}`).font = { color: { argb: C.green }, size: 8 }; });
  panelTitle(dashboard, "H10:K11", "UNIT BERULANG", "Prioritas inspeksi mendalam"); writeRow(dashboard, 12, 8, ["Unit", "Kontraktor", "Outstanding", "Total"]); styleRow(dashboard, 12, 8, 4, headerStyle); repeats.slice(0, 8).forEach((item, index) => { writeRow(dashboard, 13 + index, 8, [item.unit, item.company, item.outstanding, item.total]); dashboard.getCell(`J${13 + index}`).font = { bold: true, color: { argb: C.orange } }; });
  panelTitle(dashboard, "M10:N11", "ANTRIAN TINDAK LANJUT", "Outstanding paling mendesak"); writeRow(dashboard, 12, 13, ["Unit / kontraktor", "Umur / status"]); styleRow(dashboard, 12, 13, 2, headerStyle); active.slice().sort((a, b) => Number(Boolean(b.target_date && new Date(b.target_date).getTime() < Date.now())) - Number(Boolean(a.target_date && new Date(a.target_date).getTime() < Date.now())) || (a.target_date || "9999").localeCompare(b.target_date || "9999")).slice(0, 8).forEach((item, index) => { const row = 13 + index, late = item.target_date && new Date(item.target_date).getTime() < Date.now(); writeRow(dashboard, row, 13, [`${item.unit_number || item.finding_number} · ${item.companies?.code || "—"}\n${item.detailed_description || ""}`, `${ageDays(item.finding_date)} hari\n${late ? "OVERDUE" : statusLabel[item.current_status]}`]); dashboard.getCell(`M${row}`).alignment = { vertical: "middle", wrapText: true }; dashboard.getCell(`N${row}`).alignment = { vertical: "middle", wrapText: true }; dashboard.getCell(`N${row}`).font = { bold: true, color: { argb: late ? C.red : C.green } }; dashboard.getRow(row).height = 32; });
  const support = [{ title: "AGING OUTSTANDING", start: "A23", data: aging.map((item) => [item.name, item.value]), format: "count" }, { title: "CLOSURE RATE", start: "E23", data: companyRate.slice(0, 6).map((item) => [item.name, item.value]), format: "percent" }, { title: "KATEGORI DOMINAN", start: "I23", data: countBy(rows.map((row) => row.categories?.name || "Tanpa kategori")).slice(0, 6), format: "count" }, { title: "DISTRIBUSI SECTION", start: "M23", data: countBy(rows.map((row) => row.sections?.name || "Tanpa section")).slice(0, 6), format: "count" }];
  support.forEach((block) => { const col = block.start.match(/[A-Z]+/)![0], row = Number(block.start.match(/\d+/)![0]), end = col === "A" ? "C" : col === "E" ? "G" : col === "I" ? "K" : "N"; panelTitle(dashboard, `${col}${row}:${end}${row + 1}`, block.title, "Live snapshot dari data SISOBER"); const max = Math.max(1, ...block.data.map((item) => Number(item[1]))); block.data.forEach((item, index) => { const r = row + 2 + index; dashboard.getCell(`${col}${r}`).value = item[0]; const valueCell = dashboard.getCell(`${String.fromCharCode(col.charCodeAt(0) + 1)}${r}`); valueCell.value = item[1]; if (block.format === "percent") valueCell.numFmt = "0%"; const barCell = dashboard.getCell(`${String.fromCharCode(col.charCodeAt(0) + 2)}${r}`); barCell.value = bars(Number(item[1]), max, 12); barCell.font = { color: { argb: col === "E" ? C.green : C.orange }, size: 8 }; }); });
  const findings = workbook.addWorksheet("MASTER FINDINGS", { views: [{ state: "frozen", ySplit: 1, showGridLines: false }], properties: { defaultRowHeight: 20 } }); findings.columns = [{ header: "NO.", key: "no", width: 7 }, { header: "FINDING NUMBER", key: "number", width: 20 }, { header: "NO. ASLI", key: "original", width: 10 }, { header: "DATE", key: "date", width: 13 }, { header: "MONTH", key: "month", width: 13 }, { header: "YEARS", key: "year", width: 9 }, { header: "COMPANY CODE", key: "companyCode", width: 15 }, { header: "COMPANY NAME", key: "companyName", width: 24 }, { header: "UNIT NUMBER", key: "unit", width: 26 }, { header: "SECTION HAULING", key: "section", width: 18 }, { header: "FINDING NEGATIVE CATEGORY", key: "category", width: 42 }, { header: "SMALL REMARKS", key: "remarks", width: 45 }, { header: "KETERANGAN", key: "status", width: 23 }, { header: "TARGET DATE", key: "target", width: 14 }, { header: "CLOSED AT", key: "closed", width: 14 }, { header: "SOURCE", key: "source", width: 18 }]; rows.forEach((item, index) => { const date = new Date(`${item.finding_date}T00:00:00`), row = findings.addRow({ no: index + 1, number: item.finding_number, original: item.legacy_original_number || "", date, month: new Intl.DateTimeFormat("id-ID", { month: "long" }).format(date).toUpperCase(), year: date.getFullYear(), companyCode: item.companies?.code || "", companyName: item.companies?.name || "", unit: item.unit_number || "", section: item.sections?.name || "", category: item.categories?.name || "", remarks: item.detailed_description || "", status: statusLabel[item.current_status] || item.current_status, target: item.target_date ? new Date(`${item.target_date}T00:00:00`) : null, closed: item.closed_at ? new Date(item.closed_at) : null, source: item.source_type || "" }); row.getCell("date").numFmt = "dd-mmm-yyyy"; row.getCell("target").numFmt = "dd-mmm-yyyy"; row.getCell("closed").numFmt = "dd-mmm-yyyy"; row.alignment = { vertical: "top", wrapText: true }; if (index % 2) row.eachCell((cell) => { cell.fill = fill("F8FAF9"); }); const status = row.getCell("status"), colors: Record<string, [string, string]> = { Open: [C.orangeSoft, "A74317"], "Menunggu Verifikasi": ["E4F0F8", "24658F"], "Perlu Revisi": [C.redSoft, "A93631"], Close: [C.greenSoft, "187248"] }, pair = colors[String(status.value)] || [C.bg, C.ink]; status.fill = fill(pair[0]); status.font = { bold: true, color: { argb: pair[1] } }; }); findings.autoFilter = { from: "A1", to: "P1" }; styleTable(findings);
  const companySheet = workbook.addWorksheet("MASTER COMPANIES", { views: [{ state: "frozen", ySplit: 1, showGridLines: false }] }); companySheet.columns = [{ header: "ID", key: "id", width: 38 }, { header: "CODE", key: "code", width: 14 }, { header: "COMPANY NAME", key: "name", width: 34 }, { header: "ACTIVE", key: "active", width: 12 }]; companies.forEach((item) => companySheet.addRow(item)); styleTable(companySheet);
  const categorySheet = workbook.addWorksheet("MASTER CATEGORIES", { views: [{ state: "frozen", ySplit: 1, showGridLines: false }] }); categorySheet.columns = [{ header: "ID", key: "id", width: 38 }, { header: "CATEGORY", key: "name", width: 48 }, { header: "SHORT NAME", key: "short_name", width: 24 }, { header: "GROUP", key: "category_group", width: 24 }, { header: "EVIDENCE REQUIREMENT", key: "default_evidence_requirement", width: 24 }, { header: "ACTIVE", key: "active", width: 12 }]; categories.forEach((item) => categorySheet.addRow(item)); styleTable(categorySheet);
  const sectionSheet = workbook.addWorksheet("MASTER SECTIONS", { views: [{ state: "frozen", ySplit: 1, showGridLines: false }] }); sectionSheet.columns = [{ header: "ID", key: "id", width: 38 }, { header: "SECTION", key: "name", width: 28 }, { header: "ACTIVE", key: "active", width: 12 }]; sections.forEach((item) => sectionSheet.addRow(item)); styleTable(sectionSheet);
  const userSheet = workbook.addWorksheet("MASTER USERS", { views: [{ state: "frozen", ySplit: 1, showGridLines: false }] }); userSheet.columns = [{ header: "ID", key: "id", width: 38 }, { header: "EMAIL", key: "email", width: 32 }, { header: "FULL NAME", key: "full_name", width: 28 }, { header: "NIK", key: "nik", width: 18 }, { header: "ROLE", key: "role", width: 22 }, { header: "CONTRACTOR ACCESS", key: "companies", width: 28 }, { header: "ACTIVE", key: "active", width: 12 }, { header: "CREATED AT", key: "created_at", width: 22 }]; profiles.forEach((item) => userSheet.addRow({ ...item, companies: access.filter((entry: any) => entry.user_id === item.id).map((entry: any) => entry.companies?.code).filter(Boolean).join(", ") })); styleTable(userSheet);
  [companySheet, categorySheet, sectionSheet, userSheet].forEach((sheet) => { sheet.autoFilter = { from: "A1", to: sheet.getCell(1, sheet.columnCount).address }; });
  const buffer = await workbook.xlsx.writeBuffer(); const now = new Date(), date = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
  return new Response(buffer as ArrayBuffer, { headers: { "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Content-Disposition": `attachment; filename="SISOBER-Master-Dashboard-${date}.xlsx"`, "Cache-Control": "no-store" } });
}
